### ISSUE TITLE
[BUG]: unable to resize card with card-mod

### ISSUE THREAD

**Issue by firstcolle** [nutteloost/actions-card#2]
### Current Behavior

I’m experiencing an issue with the action card: I cannot change the card size using card-mod.

### Expected Behavior

The card should adapt to the dimensions set via card-mod.

### Steps to Reproduce

Create an action-card.

Apply card-mod to set width/height.

Notice that the card size does not change.

### Actions Card Version

1.4.2

### Home Assistant Version

2025.8.1

### Affected Feature

General / Other

### YAML Configuration

```yaml
type: custom:actions-card
card:
  type: media-control
  entity: media_player.denon
  card_mod:
    style: |
      ha-card {
      height: 500px !important;
      }
tap_action:
  action: none
hold_action:
  action: none
double_tap_action:
  action: navigate
  navigation_path: /lovelace/media-player
prevent_default_dialog: false
```

### Screenshots or Console Errors

<img width="999" height="528" alt="Image" src="https://github.com/user-attachments/assets/2eee06fc-4b98-4e90-bf08-7b19d03f25f5" />

### Pre-Submission Checklist

- [x] I have searched existing [issues](https://github.com/nutteloost/actions-card/issues) to ensure this bug hasn't been reported.
- [x] I have provided steps to reproduce the bug.
- [x] I have included the YAML configuration to reproduce the issue.

**Comment by firstcolle** [comment]
thanks for your release.
Now the card has the size set in card-mod, but the following cards that should go underneath are overlapping.

<img width="468" height="325" alt="Image" src="https://github.com/user-attachments/assets/39c04365-9bfe-41b7-90c3-97c72dd5b2c4" />

it should be like this:

<img width="484" height="346" alt="Image" src="https://github.com/user-attachments/assets/5b1cf37a-1b20-4ebc-89c8-9e9121f89d41" />

**Comment by nutteloost** [comment]
Please try [v1.4.4](https://github.com/nutteloost/actions-card/releases/tag/v1.4.4), this should fix it!

**Comment by firstcolle** [comment]
Unfortunately, I still have the same behavior

<img width="397" height="275" alt="Image" src="https://github.com/user-attachments/assets/7fa98f73-7e33-4995-be25-06fc4f5cf1e2" />

**Comment by firstcolle** [comment]
nothing to do.. i've also restarted ha aed used a new browser..

**Comment by firstcolle** [comment]
3.4.5, is the last that i can install

**Comment by firstcolle** [comment]
I tried reinstalling version 1.4.5 and completely recreating the card. Now it works!!! I probably had something wrong in the code. I'm closing the issue.
many thanks
